// Career Database with Profile Vectors
// Each career has scores for different attributes (0-1 scale)

export const careers = [
    {
        id: 1,
        name: "Software Engineer",
        description: "Design, develop, and maintain software applications and systems. Work on everything from web apps to mobile apps to complex backend systems.",
        category: "Technology",
        icon: "💻",
        salary: "$80,000 - $150,000",
        demand: "Very High",
        growth: "+25%",
        education: "Bachelor's in Computer Science or related field",
        skills: ["Programming", "Problem Solving", "Algorithms", "System Design"],
        // Profile Vector
        analytical: 0.9,
        creativity: 0.5,
        communication: 0.4,
        techSkill: 0.95,
        leadership: 0.3,
        empathy: 0.3,
        practical: 0.7,
        dataOriented: 0.8,
        peopleOriented: 0.3,
        independence: 0.7
    },
    {
        id: 2,
        name: "UI/UX Designer",
        description: "Create intuitive and visually appealing user interfaces. Research user behavior and design experiences that delight users.",
        category: "Design",
        icon: "🎨",
        salary: "$70,000 - $130,000",
        demand: "High",
        growth: "+20%",
        education: "Bachelor's in Design, HCI, or related field",
        skills: ["Visual Design", "User Research", "Prototyping", "Design Tools"],
        analytical: 0.6,
        creativity: 0.95,
        communication: 0.7,
        techSkill: 0.6,
        leadership: 0.4,
        empathy: 0.85,
        practical: 0.6,
        dataOriented: 0.5,
        peopleOriented: 0.7,
        independence: 0.6
    },
    {
        id: 3,
        name: "Data Scientist",
        description: "Analyze complex data sets to identify patterns and insights. Use machine learning and statistical methods to solve business problems.",
        category: "Technology",
        icon: "📊",
        salary: "$90,000 - $160,000",
        demand: "Very High",
        growth: "+30%",
        education: "Master's in Data Science, Statistics, or related field",
        skills: ["Python/R", "Machine Learning", "Statistics", "Data Visualization"],
        analytical: 0.95,
        creativity: 0.5,
        communication: 0.5,
        techSkill: 0.85,
        leadership: 0.3,
        empathy: 0.3,
        practical: 0.7,
        dataOriented: 0.95,
        peopleOriented: 0.2,
        independence: 0.7
    },
    {
        id: 4,
        name: "Product Manager",
        description: "Define product vision and strategy. Work with cross-functional teams to deliver products that meet customer needs.",
        category: "Business",
        icon: "📱",
        salary: "$100,000 - $170,000",
        demand: "High",
        growth: "+15%",
        education: "Bachelor's in Business, Engineering, or related field",
        skills: ["Strategy", "Communication", "Analytics", "Leadership"],
        analytical: 0.7,
        creativity: 0.6,
        communication: 0.9,
        techSkill: 0.5,
        leadership: 0.85,
        empathy: 0.7,
        practical: 0.7,
        dataOriented: 0.6,
        peopleOriented: 0.8,
        independence: 0.5
    },
    {
        id: 5,
        name: "Psychologist",
        description: "Study human behavior and mental processes. Help individuals overcome challenges and improve their mental well-being.",
        category: "Healthcare",
        icon: "🧠",
        salary: "$60,000 - $120,000",
        demand: "High",
        growth: "+15%",
        education: "Doctorate in Psychology",
        skills: ["Active Listening", "Empathy", "Analysis", "Communication"],
        analytical: 0.7,
        creativity: 0.5,
        communication: 0.9,
        techSkill: 0.2,
        leadership: 0.4,
        empathy: 0.95,
        practical: 0.5,
        dataOriented: 0.4,
        peopleOriented: 0.95,
        independence: 0.6
    },
    {
        id: 6,
        name: "Marketing Manager",
        description: "Develop and execute marketing strategies to promote products and services. Analyze market trends and consumer behavior.",
        category: "Business",
        icon: "📣",
        salary: "$70,000 - $140,000",
        demand: "High",
        growth: "+12%",
        education: "Bachelor's in Marketing or Business",
        skills: ["Strategy", "Creative Thinking", "Analytics", "Communication"],
        analytical: 0.6,
        creativity: 0.8,
        communication: 0.9,
        techSkill: 0.4,
        leadership: 0.7,
        empathy: 0.6,
        practical: 0.6,
        dataOriented: 0.6,
        peopleOriented: 0.8,
        independence: 0.5
    },
    {
        id: 7,
        name: "Mechanical Engineer",
        description: "Design, develop, and test mechanical devices and systems. Work on everything from engines to robotics.",
        category: "Engineering",
        icon: "⚙️",
        salary: "$70,000 - $130,000",
        demand: "Medium",
        growth: "+8%",
        education: "Bachelor's in Mechanical Engineering",
        skills: ["CAD Software", "Problem Solving", "Mathematics", "Physics"],
        analytical: 0.85,
        creativity: 0.6,
        communication: 0.4,
        techSkill: 0.7,
        leadership: 0.3,
        empathy: 0.2,
        practical: 0.9,
        dataOriented: 0.6,
        peopleOriented: 0.3,
        independence: 0.6
    },
    {
        id: 8,
        name: "Graphic Designer",
        description: "Create visual content for brands, including logos, advertisements, and digital media. Combine art and technology.",
        category: "Design",
        icon: "🖌️",
        salary: "$50,000 - $90,000",
        demand: "Medium",
        growth: "+5%",
        education: "Bachelor's in Graphic Design or Fine Arts",
        skills: ["Adobe Creative Suite", "Typography", "Color Theory", "Creativity"],
        analytical: 0.3,
        creativity: 0.95,
        communication: 0.5,
        techSkill: 0.5,
        leadership: 0.2,
        empathy: 0.5,
        practical: 0.5,
        dataOriented: 0.2,
        peopleOriented: 0.4,
        independence: 0.8
    },
    {
        id: 9,
        name: "Financial Analyst",
        description: "Analyze financial data to guide investment decisions. Prepare reports and forecasts for businesses.",
        category: "Finance",
        icon: "💰",
        salary: "$65,000 - $120,000",
        demand: "High",
        growth: "+10%",
        education: "Bachelor's in Finance or Accounting",
        skills: ["Excel", "Financial Modeling", "Analysis", "Attention to Detail"],
        analytical: 0.95,
        creativity: 0.3,
        communication: 0.5,
        techSkill: 0.5,
        leadership: 0.3,
        empathy: 0.2,
        practical: 0.7,
        dataOriented: 0.95,
        peopleOriented: 0.3,
        independence: 0.6
    },
    {
        id: 10,
        name: "Teacher / Educator",
        description: "Educate and inspire students. Develop curriculum and create engaging learning experiences.",
        category: "Education",
        icon: "📚",
        salary: "$45,000 - $80,000",
        demand: "High",
        growth: "+5%",
        education: "Bachelor's in Education + Teaching Certification",
        skills: ["Communication", "Patience", "Creativity", "Organization"],
        analytical: 0.5,
        creativity: 0.7,
        communication: 0.95,
        techSkill: 0.3,
        leadership: 0.6,
        empathy: 0.9,
        practical: 0.6,
        dataOriented: 0.3,
        peopleOriented: 0.95,
        independence: 0.4
    },
    {
        id: 11,
        name: "Entrepreneur",
        description: "Start and run your own business. Identify opportunities, take risks, and build something from the ground up.",
        category: "Business",
        icon: "🚀",
        salary: "Variable - $0 to $1M+",
        demand: "Self-Driven",
        growth: "Unlimited",
        education: "Any (Experience matters more)",
        skills: ["Leadership", "Risk-Taking", "Problem Solving", "Networking"],
        analytical: 0.7,
        creativity: 0.8,
        communication: 0.8,
        techSkill: 0.4,
        leadership: 0.95,
        empathy: 0.6,
        practical: 0.8,
        dataOriented: 0.5,
        peopleOriented: 0.7,
        independence: 0.95
    },
    {
        id: 12,
        name: "Cybersecurity Analyst",
        description: "Protect organizations from cyber threats. Monitor, detect, and respond to security incidents.",
        category: "Technology",
        icon: "🔐",
        salary: "$80,000 - $150,000",
        demand: "Very High",
        growth: "+35%",
        education: "Bachelor's in Cybersecurity or IT",
        skills: ["Security Tools", "Problem Solving", "Attention to Detail", "Networking"],
        analytical: 0.9,
        creativity: 0.4,
        communication: 0.4,
        techSkill: 0.9,
        leadership: 0.3,
        empathy: 0.2,
        practical: 0.8,
        dataOriented: 0.7,
        peopleOriented: 0.2,
        independence: 0.7
    },
    {
        id: 13,
        name: "Content Writer",
        description: "Create compelling written content for websites, blogs, marketing, and social media.",
        category: "Creative",
        icon: "✍️",
        salary: "$45,000 - $85,000",
        demand: "High",
        growth: "+12%",
        education: "Bachelor's in English, Journalism, or Communications",
        skills: ["Writing", "Research", "SEO", "Creativity"],
        analytical: 0.5,
        creativity: 0.9,
        communication: 0.85,
        techSkill: 0.3,
        leadership: 0.2,
        empathy: 0.6,
        practical: 0.5,
        dataOriented: 0.4,
        peopleOriented: 0.5,
        independence: 0.85
    },
    {
        id: 14,
        name: "Nurse",
        description: "Provide direct patient care in hospitals, clinics, or home settings. A rewarding career in healthcare.",
        category: "Healthcare",
        icon: "🏥",
        salary: "$60,000 - $110,000",
        demand: "Very High",
        growth: "+15%",
        education: "Bachelor's or Associate's in Nursing + RN License",
        skills: ["Patient Care", "Communication", "Medical Knowledge", "Empathy"],
        analytical: 0.6,
        creativity: 0.3,
        communication: 0.8,
        techSkill: 0.4,
        leadership: 0.4,
        empathy: 0.95,
        practical: 0.9,
        dataOriented: 0.4,
        peopleOriented: 0.95,
        independence: 0.4
    },
    {
        id: 15,
        name: "Architect",
        description: "Design buildings and structures. Combine artistic vision with engineering principles.",
        category: "Design",
        icon: "🏛️",
        salary: "$70,000 - $130,000",
        demand: "Medium",
        growth: "+8%",
        education: "Bachelor's + Master's in Architecture",
        skills: ["Design Software", "Creativity", "Engineering", "Attention to Detail"],
        analytical: 0.7,
        creativity: 0.9,
        communication: 0.5,
        techSkill: 0.6,
        leadership: 0.4,
        empathy: 0.4,
        practical: 0.8,
        dataOriented: 0.5,
        peopleOriented: 0.4,
        independence: 0.6
    },
    {
        id: 16,
        name: "Human Resources Manager",
        description: "Manage employee relations, recruitment, and organizational culture. Bridge between employees and management.",
        category: "Business",
        icon: "👥",
        salary: "$65,000 - $120,000",
        demand: "High",
        growth: "+10%",
        education: "Bachelor's in HR, Business, or Psychology",
        skills: ["Communication", "Conflict Resolution", "Organization", "Empathy"],
        analytical: 0.5,
        creativity: 0.4,
        communication: 0.9,
        techSkill: 0.3,
        leadership: 0.7,
        empathy: 0.85,
        practical: 0.6,
        dataOriented: 0.4,
        peopleOriented: 0.95,
        independence: 0.4
    },
    {
        id: 17,
        name: "Game Developer",
        description: "Create video games for various platforms. Combine programming with creative storytelling and design.",
        category: "Technology",
        icon: "🎮",
        salary: "$60,000 - $130,000",
        demand: "High",
        growth: "+20%",
        education: "Bachelor's in Game Development, CS, or related field",
        skills: ["Programming", "Game Engines", "Creativity", "3D Modeling"],
        analytical: 0.8,
        creativity: 0.85,
        communication: 0.4,
        techSkill: 0.9,
        leadership: 0.3,
        empathy: 0.4,
        practical: 0.7,
        dataOriented: 0.5,
        peopleOriented: 0.3,
        independence: 0.7
    },
    {
        id: 18,
        name: "Environmental Scientist",
        description: "Study the environment and develop solutions to environmental problems. Work on sustainability and conservation.",
        category: "Science",
        icon: "🌍",
        salary: "$55,000 - $100,000",
        demand: "High",
        growth: "+12%",
        education: "Bachelor's or Master's in Environmental Science",
        skills: ["Research", "Data Analysis", "Fieldwork", "Report Writing"],
        analytical: 0.8,
        creativity: 0.5,
        communication: 0.6,
        techSkill: 0.5,
        leadership: 0.3,
        empathy: 0.7,
        practical: 0.8,
        dataOriented: 0.7,
        peopleOriented: 0.4,
        independence: 0.6
    },
    {
        id: 19,
        name: "Lawyer / Attorney",
        description: "Provide legal advice and represent clients in legal matters. Specialize in various areas of law.",
        category: "Law",
        icon: "⚖️",
        salary: "$80,000 - $200,000",
        demand: "High",
        growth: "+8%",
        education: "Juris Doctor (JD) + Bar Exam",
        skills: ["Research", "Argumentation", "Communication", "Critical Thinking"],
        analytical: 0.9,
        creativity: 0.5,
        communication: 0.95,
        techSkill: 0.3,
        leadership: 0.6,
        empathy: 0.5,
        practical: 0.6,
        dataOriented: 0.6,
        peopleOriented: 0.7,
        independence: 0.6
    },
    {
        id: 20,
        name: "Chef / Culinary Artist",
        description: "Create delicious dishes and manage kitchen operations. Combine creativity with culinary expertise.",
        category: "Hospitality",
        icon: "👨‍🍳",
        salary: "$40,000 - $90,000",
        demand: "Medium",
        growth: "+10%",
        education: "Culinary School or Apprenticeship",
        skills: ["Cooking Techniques", "Creativity", "Leadership", "Time Management"],
        analytical: 0.4,
        creativity: 0.9,
        communication: 0.5,
        techSkill: 0.3,
        leadership: 0.6,
        empathy: 0.5,
        practical: 0.95,
        dataOriented: 0.2,
        peopleOriented: 0.5,
        independence: 0.6
    }
];

// Get careers by category
export const getCareersByCategory = (category) => {
    return careers.filter(career => career.category === category);
};

// Get all unique categories
export const getCategories = () => {
    return [...new Set(careers.map(career => career.category))];
};

// Get career by ID
export const getCareerById = (id) => {
    return careers.find(career => career.id === id);
};
